name: Build slide for CW24 lightning talk
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile slide
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cw24.tex
          latexmk_use_lualatex: true
      - name: Upload slide PDF file
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: cw24.pdf
      - name: Set Git user identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
      - name: Create tag
        run: git tag -a v${{ steps.timestamp.outputs.timestamp }} -m "Version v${{ steps.timestamp.outputs.timestamp }}"
      - name: Push tag
        run: git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: cw24.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
