name: Build slide for CW24 lightning talk
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile slide
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cw24.tex
          latexmk_use_lualatex: true
      - name: Upload slide PDF file
        uses: actions/upload-artifact@v3
        with:
          name: cw24
          path: cw24.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cw24.pdf
